[project]
name = "rock-paper-seciser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Fardeel Azhar", email = "fardeelazhar82@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "autogen-agentchat>=0.7.5",
    "autogen-core>=0.7.5",
    "autogen-ext[ollama,openai]>=0.7.5",
    "python-dotenv>=1.2.3",
]

[project.scripts]
rock-paper-seciser = "rock_paper_seciser:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
